POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "Davies2",
    "password": "Damilola12?"
}

###

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "username": "Davies2",
    "password": "Damilola12?"
}
###